### ISSUE TITLE
REQUEST: can you post instructions?

### ISSUE THREAD

**Issue by deanhuff** [Candygoblen123/macos-wii-u-vc-injection#1]
can you post instructions on how to use this tool?

**Comment by Candygoblen123** [comment]
Sorry for the late reply, but this program is not in a working state right now, but I will be sure to write a guide on how to use it when I actually push a release.


________________________________

**Comment by deanhuff** [comment]
no worries, i'll keep an eyout on your progress.  in the meantime i'm using a windows 7 virtual box and it gets the job done.
